// lib/mockListings.ts
export interface Listing {
  id: string;
  title: string;
  location: string;
  images: string[];
  price: number; // Changed from string to number
  rating: number;
  distance: string;
  dateRange: string;
  isNew?: boolean;
  guestFavorite?: boolean;
  bedrooms: number;
  bathrooms: number;
  description: string;
  amenities: string[];
  reviews: number;
  host: string;
  guests: number;
}

export const listings: Listing[] = [
  {
    id: "1",
    title: "Cozy Beachfront Studio",
    location: "Malibu, CA",
    images: [
      "/images/c.jpg",
      "/images/c.jpg",
      "/images/c.jpg",
      "/images/c.jpg",
    ],
    price: 350,
    rating: 4.8,
    distance: "5 miles away",
    dateRange: "Jul 10 - 15",
    isNew: true,
    guestFavorite: true,
    bedrooms: 1,
    bathrooms: 1,
    description: "A cozy studio right on the beach, perfect for a romantic getaway with stunning ocean views and direct beach access.",
    amenities: ["WiFi", "Kitchenette", "Beach Access", "Free Parking"],
    reviews: 128,
    host: "Sarah Johnson",
    guests: 2,
  },
  {
    id: "2",
    title: "Historic Downtown Loft",
    location: "Charleston, SC",
    images: [
      "/images/c.jpg",
      "/images/listing2_2.jpg",
      "/images/listing2_3.jpg",
    ],
    price: 280,
    rating: 4.7,
    distance: "2 miles away",
    dateRange: "Aug 1 - 5",
    isNew: false,
    guestFavorite: true,
    bedrooms: 2,
    bathrooms: 1.5,
    description: "Experience the charm of Charleston in this beautifully restored historic loft, steps away from vibrant shops and restaurants.",
    amenities: ["WiFi", "Full Kitchen", "Air Conditioning", "City View"],
    reviews: 95,
    host: "Michael Davis",
    guests: 4,
  },
  {
    id: "3",
    title: "Mountain Retreat with Hot Tub",
    location: "Asheville, NC",
    images: [
      "/images/c.jpg",
      "/images/listing3_2.jpg",
      "/images/listing3_3.jpg",
      "/images/listing3_4.jpg",
    ],
    price: 420,
    rating: 4.9,
    distance: "15 miles away",
    dateRange: "Sep 3 - 9",
    isNew: true,
    guestFavorite: false,
    bedrooms: 3,
    bathrooms: 2,
    description: "Escape to the mountains in this serene retreat featuring a private hot tub, breathtaking views, and easy access to hiking trails.",
    amenities: ["WiFi", "Hot Tub", "Fireplace", "Mountain View", "Pet-friendly"],
    reviews: 150,
    host: "Emily White",
    guests: 6,
  },
  {
    id: "4",
    title: "Urban Oasis with Rooftop Pool",
    location: "Miami, FL",
    images: [
      "/images/c.jpg",
      "/images/listing4_2.jpg",
      "/images/listing4_3.jpg",
    ],
    price: 600,
    rating: 4.6,
    distance: "Downtown",
    dateRange: "Oct 12 - 18",
    isNew: false,
    guestFavorite: false,
    bedrooms: 2,
    bathrooms: 2,
    description: "Luxurious urban apartment with access to a stunning rooftop pool, offering panoramic cityscapes in the heart of Miami.",
    amenities: ["WiFi", "Rooftop Pool", "Gym", "Parking", "Concierge"],
    reviews: 70,
    host: "David Chen",
    guests: 4,
  },
  {
    id: "5",
    title: "Secluded Lakeside Cabin",
    location: "Lake Tahoe, CA",
    images: [
      "/images/c.jpg",
      "/images/listing5_2.jpg",
      "/images/listing5_3.jpg",
      "/images/listing5_4.jpg",
    ],
    price: 550,
    rating: 4.9,
    distance: "20 miles away",
    dateRange: "Nov 5 - 10",
    isNew: true,
    guestFavorite: false,
    bedrooms: 4,
    bathrooms: 2.5,
    description: "A tranquil cabin nestled by the serene waters of Lake Tahoe, perfect for nature lovers and quiet escapes.",
    amenities: ["WiFi", "Lake Access", "Fire Pit", "Boat Dock", "BBQ Grill"],
    reviews: 110,
    host: "Jessica Lee",
    guests: 8,
  },
  {
    id: "6",
    title: "Charming Cottage by the Vineyards",
    location: "Napa Valley, CA",
    images: [
      "/images/c.jpg",
      "/images/listing6_2.jpg",
      "/images/listing6_3.jpg",
    ],
    price: 700,
    rating: 4.8,
    distance: "10 miles away",
    dateRange: "Dec 1 - 7",
    isNew: true,
    guestFavorite: false,
    bedrooms: 2,
    bathrooms: 2,
    description: "Sip wine and relax in this charming cottage surrounded by picturesque vineyards, offering an authentic Napa Valley experience.",
    amenities: ["WiFi", "Vineyard Views", "Wine Tasting nearby", "Private Patio"],
    reviews: 60,
    host: "Robert Brown",
    guests: 3,
  },
  {
    id: "7",
    title: "Spacious Family Home with Garden",
    location: "Denver, CO",
    images: [
      "/images/c.jpg",
      "/images/listing7_2.jpg",
      "/images/listing7_3.jpg",
      "/images/listing7_4.jpg",
    ],
    price: 380,
    rating: 4.5,
    distance: "Suburb",
    dateRange: "Jan 15 - 20",
    isNew: false,
    guestFavorite: false,
    bedrooms: 4,
    bathrooms: 3,
    description: "A spacious and inviting family home with a beautiful garden, ideal for larger groups looking for comfort and relaxation.",
    amenities: ["WiFi", "Large Garden", "B_B_Q Grill", "Kid-friendly", "Washing Machine"],
    reviews: 85,
    host: "Laura Green",
    guests: 7,
  },
  {
    id: "8",
    title: "Artist's Loft in Creative District",
    location: "Portland, OR",
    images: [
      "/images/c.jpg",
      "/images/listing8_2.jpg",
      "/images/listing8_3.jpg",
    ],
    price: 310,
    rating: 4.7,
    distance: "Central",
    dateRange: "Feb 2 - 8",
    isNew: true,
    guestFavorite: true,
    bedrooms: 1,
    bathrooms: 1,
    description: "Immerse yourself in art and culture in this stylish artist's loft located in Portland's vibrant creative district.",
    amenities: ["WiFi", "Workspace", "City View", "Near Galleries"],
    reviews: 105,
    host: "Daniel Kim",
    guests: 2,
  },
  {
    id: "9",
    title: "Desert Oasis with Stargazing",
    location: "Joshua Tree, CA",
    images: [
      "/images/c.jpg",
      "/images/listing9_2.jpg",
      "/images/listing9_3.jpg",
      "/images/listing9_4.jpg",
    ],
    price: 490,
    rating: 4.9,
    distance: "Remote",
    dateRange: "Mar 1 - 6",
    isNew: true,
    guestFavorite: false,
    bedrooms: 2,
    bathrooms: 1.5,
    description: "Find tranquility in this desert oasis, offering unparalleled stargazing opportunities and a unique Joshua Tree experience.",
    amenities: ["WiFi", "Stargazing Deck", "Fire Pit", "Hiking Trails nearby"],
    reviews: 45,
    host: "Sophia Rodriguez",
    guests: 4,
  },
  {
    id: "10",
    title: "Ski-in/Ski-out Condo",
    location: "Aspen, CO",
    images: [
      "/images/c.jpg",
      "/images/listing10_2.jpg",
      "/images/listing10_3.jpg",
    ],
    price: 950,
    rating: 4.8,
    distance: "On mountain",
    dateRange: "Apr 10 - 16",
    isNew: false,
    guestFavorite: true,
    bedrooms: 3,
    bathrooms: 3,
    description: "Hit the slopes directly from this luxurious ski-in/ski-out condo, offering prime access to Aspen's world-class skiing.",
    amenities: ["WiFi", "Ski-in/Ski-out", "Fireplace", "Heated Pool", "Gym"],
    reviews: 80,
    host: "James Taylor",
    guests: 6,
  },
  {
    id: "11",
    title: "Luxury Penthouse with City Views",
    location: "Chicago, IL",
    images: [
      "/images/c.jpg",
      "/images/listing11_2.jpg",
      "/images/listing11_3.jpg",
      "/images/listing11_4.jpg",
    ],
    price: 1100,
    rating: 4.9,
    distance: "Financial District",
    dateRange: "May 20 - 25",
    isNew: true,
    guestFavorite: false,
    bedrooms: 3,
    bathrooms: 3.5,
    description: "Indulge in unparalleled luxury in this penthouse, boasting stunning panoramic city views of Chicago's iconic skyline.",
    amenities: ["WiFi", "City Views", "Private Balcony", "Concierge", "Gym"],
    reviews: 30,
    host: "Olivia Martinez",
    guests: 5,
  },
  {
    id: "12",
    title: "Quaint Farmhouse Experience",
    location: "Vermont, VT",
    images: [
      "/images/c.jpg",
      "/images/listing12_2.jpg",
      "/images/listing12_3.jpg",
    ],
    price: 220,
    rating: 4.6,
    distance: "Countryside",
    dateRange: "Jun 1 - 7",
    isNew: false,
    guestFavorite: false,
    bedrooms: 3,
    bathrooms: 2,
    description: "Experience the charm of rural Vermont in this quaint farmhouse, surrounded by rolling hills and peaceful countryside.",
    amenities: ["WiFi", "Garden", "Farm Animals", "Hiking Trails nearby"],
    reviews: 140,
    host: "William Johnson",
    guests: 5,
  },
  {
    id: "13",
    title: "Bohemian Bungalow by the Beach",
    location: "San Diego, CA",
    images: [
      "/images/c.jpg",
      "/images/listing13_2.jpg",
      "/images/listing13_3.jpg",
      "/images/listing13_4.jpg",
    ],
    price: 400,
    rating: 4.7,
    distance: "Beachfront",
    dateRange: "Jul 4 - 9",
    isNew: true,
    guestFavorite: false,
    bedrooms: 2,
    bathrooms: 1,
    description: "A vibrant and cozy bohemian bungalow just steps from the sandy beaches of San Diego, perfect for surf lovers.",
    amenities: ["WiFi", "Beach Access", "Outdoor Shower", "Surfboard Storage"],
    reviews: 90,
    host: "Ava Garcia",
    guests: 3,
  },
  {
    id: "14",
    title: "Historic Brownstone Apartment",
    location: "Boston, MA",
    images: [
      "/images/c.jpg",
      "/images/listing14_2.jpg",
      "/images/listing14_3.jpg",
    ],
    price: 330,
    rating: 4.8,
    distance: "Beacon Hill",
    dateRange: "Aug 20 - 24",
    isNew: true,
    guestFavorite: true,
    bedrooms: 1,
    bathrooms: 1,
    description: "Immerse yourself in Boston's rich history in this elegant brownstone apartment located in the charming Beacon Hill neighborhood.",
    amenities: ["WiFi", "Historic Charm", "City View", "Near Public Transport"],
    reviews: 115,
    host: "Noah Wilson",
    guests: 2,
  },
  {
    id: "15",
    title: "Private Island Paradise",
    location: "Fiji",
    images: [
      "/images/c.jpg",
      "/images/listing15_2.jpg",
      "/images/listing15_3.jpg",
      "/images/listing15_4.jpg",
    ],
    price: 2500,
    rating: 5.0,
    distance: "Exclusive",
    dateRange: "Anytime",
    isNew: true,
    guestFavorite: true,
    bedrooms: 5,
    bathrooms: 5,
    description: "Experience the ultimate luxury on your own private island in Fiji, with pristine beaches and unparalleled seclusion.",
    amenities: ["Private Beach", "Snorkeling Gear", "Chef Services", "Boat Tours", "Spa Services"],
    reviews: 25,
    host: "Isabella Clark",
    guests: 10,
  },
];